//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.27 at 11:35:36 PM PST 
//


package amit.nmapscans.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the amit.nmapscans.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: amit.nmapscans.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nmaprun }
     * 
     */
    public Nmaprun createNmaprun() {
        return new Nmaprun();
    }

    /**
     * Create an instance of {@link Nmaprun.Runstats }
     * 
     */
    public Nmaprun.Runstats createNmaprunRunstats() {
        return new Nmaprun.Runstats();
    }

    /**
     * Create an instance of {@link Nmaprun.Host }
     * 
     */
    public Nmaprun.Host createNmaprunHost() {
        return new Nmaprun.Host();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Trace }
     * 
     */
    public Nmaprun.Host.Trace createNmaprunHostTrace() {
        return new Nmaprun.Host.Trace();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Os }
     * 
     */
    public Nmaprun.Host.Os createNmaprunHostOs() {
        return new Nmaprun.Host.Os();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ports }
     * 
     */
    public Nmaprun.Host.Ports createNmaprunHostPorts() {
        return new Nmaprun.Host.Ports();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ports.Port }
     * 
     */
    public Nmaprun.Host.Ports.Port createNmaprunHostPortsPort() {
        return new Nmaprun.Host.Ports.Port();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Hostnames }
     * 
     */
    public Nmaprun.Host.Hostnames createNmaprunHostHostnames() {
        return new Nmaprun.Host.Hostnames();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Nmaprun.Scaninfo }
     * 
     */
    public Nmaprun.Scaninfo createNmaprunScaninfo() {
        return new Nmaprun.Scaninfo();
    }

    /**
     * Create an instance of {@link Nmaprun.Verbose }
     * 
     */
    public Nmaprun.Verbose createNmaprunVerbose() {
        return new Nmaprun.Verbose();
    }

    /**
     * Create an instance of {@link Nmaprun.Debugging }
     * 
     */
    public Nmaprun.Debugging createNmaprunDebugging() {
        return new Nmaprun.Debugging();
    }

    /**
     * Create an instance of {@link Nmaprun.Output }
     * 
     */
    public Nmaprun.Output createNmaprunOutput() {
        return new Nmaprun.Output();
    }

    /**
     * Create an instance of {@link Nmaprun.Runstats.Finished }
     * 
     */
    public Nmaprun.Runstats.Finished createNmaprunRunstatsFinished() {
        return new Nmaprun.Runstats.Finished();
    }

    /**
     * Create an instance of {@link Nmaprun.Runstats.Hosts }
     * 
     */
    public Nmaprun.Runstats.Hosts createNmaprunRunstatsHosts() {
        return new Nmaprun.Runstats.Hosts();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Status }
     * 
     */
    public Nmaprun.Host.Status createNmaprunHostStatus() {
        return new Nmaprun.Host.Status();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Address }
     * 
     */
    public Nmaprun.Host.Address createNmaprunHostAddress() {
        return new Nmaprun.Host.Address();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Uptime }
     * 
     */
    public Nmaprun.Host.Uptime createNmaprunHostUptime() {
        return new Nmaprun.Host.Uptime();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Tcpsequence }
     * 
     */
    public Nmaprun.Host.Tcpsequence createNmaprunHostTcpsequence() {
        return new Nmaprun.Host.Tcpsequence();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ipidsequence }
     * 
     */
    public Nmaprun.Host.Ipidsequence createNmaprunHostIpidsequence() {
        return new Nmaprun.Host.Ipidsequence();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Tcptssequence }
     * 
     */
    public Nmaprun.Host.Tcptssequence createNmaprunHostTcptssequence() {
        return new Nmaprun.Host.Tcptssequence();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Trace.Hop }
     * 
     */
    public Nmaprun.Host.Trace.Hop createNmaprunHostTraceHop() {
        return new Nmaprun.Host.Trace.Hop();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Os.Portused }
     * 
     */
    public Nmaprun.Host.Os.Portused createNmaprunHostOsPortused() {
        return new Nmaprun.Host.Os.Portused();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Os.Osclass }
     * 
     */
    public Nmaprun.Host.Os.Osclass createNmaprunHostOsOsclass() {
        return new Nmaprun.Host.Os.Osclass();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Os.Osmatch }
     * 
     */
    public Nmaprun.Host.Os.Osmatch createNmaprunHostOsOsmatch() {
        return new Nmaprun.Host.Os.Osmatch();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ports.Extraports }
     * 
     */
    public Nmaprun.Host.Ports.Extraports createNmaprunHostPortsExtraports() {
        return new Nmaprun.Host.Ports.Extraports();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ports.Port.State }
     * 
     */
    public Nmaprun.Host.Ports.Port.State createNmaprunHostPortsPortState() {
        return new Nmaprun.Host.Ports.Port.State();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Ports.Port.Service }
     * 
     */
    public Nmaprun.Host.Ports.Port.Service createNmaprunHostPortsPortService() {
        return new Nmaprun.Host.Ports.Port.Service();
    }

    /**
     * Create an instance of {@link Nmaprun.Host.Hostnames.Hostname }
     * 
     */
    public Nmaprun.Host.Hostnames.Hostname createNmaprunHostHostnamesHostname() {
        return new Nmaprun.Host.Hostnames.Hostname();
    }

}
